### PR TITLE
Add some editors <3

### PR DESCRIPTION
**Pull request by vors**
- SublimeText
- Atom
-  ~~VSCode~~

### CODE REVIEW

**Comment by daviwil** [comment]
VS Code extension is already there, but the other two I missed!

**Comment by vors** [comment]
Oh didn't noticed!
Can I rename it into "VSCode plugin"?
I got tired while reading "PowerShell for Visual Studio Code" and that's how I missed it 😝 
Also the leading "PowerShell " word is pretty redundant in the context of this list.

**Comment by daviwil** [comment]
Sure, but I'd say spell out the VS part at least :)

**Comment by vors** [comment]
I removed it from the PR. We can do it as a separate change. I'd also like to highlight the fact that it's the only IDE that is cross-platform at the present moment.

**Pull request merged**
